name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - uses: actions/checkout@v4

      - name: Check formatting, unused modules and suspicious code
        run: |
          go fmt ./...
          go mod tidy
          git diff --exit-code
          go vet ./...

      - name: Build and test project
        run: |
          go test ./...
          mkdir bin
          GOBIN="$PWD/bin" CGO_ENABLED=0 go install ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/
